adweb_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls', namespace='product')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from django.urls import path
from .views import Index, Product

app_name = 'product'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('produtos/<int:pk>', Product.as_view(), name='product_page'),
] 

produto/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

CATEGORY_LIST = (
    ("TECNOLOGIA", "Tecnologia"),
    ("ALIMENTO", "Alimento"),
    ("CASA", "Casa"),
    ("LAZER", "Lazer"),
    ("JARDINAGEM", "Jardinagem"),
    ("CONSTRUCAO", "Construção"),
    ("OUTROS", "Outros"),
)

class Produto(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=20, choices=CATEGORY_LIST)
    price = models.FloatField()
    desc = models.TextField(max_length=1000)
    thumb = models.ImageField(upload_to='products_thumb')
    creation_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

produto/views.py
from django.shortcuts import render
from .models import Produto
from django.views.generic import ListView, DetailView

# Create your views here.

class Index(ListView):
    template_name = "index.html"
    model = Produto
    

class Product(DetailView):
    template_name = "product.html"
    model = Produto

produto/templates/index.html
{% extends 'base.html' %} 
{% block title %} Produtos {% endblock %} 
{% block content %}


<div class="shop">
  <div class="sidebar">
    <ul>
      <li class="product-category active">Todos</li>
      <li class="product-category">Tecnologia</li>
      <li class="product-category">Alimento</li>
      <li class="product-category">Casa</li>
      <li class="product-category">Lazer</li>
      <li class="product-category">Jardinagem</li>
      <li class="product-category">Construção</li>
      <li class="product-category">Outros</li>
    </ul>
  </div>

  <div class="products">
    {% for product in object_list %}
    <a href="{% url 'product:product_page' product.id %}">
      <div class="product-card">
        <img src="{{ product.thumb.url }}" alt="Imagem produto" />
        <div class="product-text">
          <div class="product-category">{{ product.category.capitalize }}</div>
          <div class="product-price">R$ {{ product.price }}</div>
          <div class="product-name">{{ product.name }}</div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>

{% endblock %}

produto/templates/product.html
{% extends 'base.html' %} 
{% block title %} {{ object }} {% endblock %} 

{% block content %}

<section class="product-page">
  <img src="{{ object.thumb.url }}" alt="Imagem do produto" />
  <hr class="d-none">
  <div class="product-page-infos">
    <span class="bold">Categoria: </span>
    <p class="product-page-desc">{{ object.category.capitalize }}</p>
    <span class="bold">Nome: </span>
    <div class="product-page-name">{{ object.name }}</div>
    <span class="bold">Descrição: </span>
    <p class="product-page-desc">{{ object.desc }}</p>
    <p class="product-price">R$ {{ object.price }}</p>
    
    <a href="#" class="buy mt-3">Comprar</a>
  </div>
</section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block head %}

    {% endblock %}
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}
    
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav
  class="navbar navbar-expand-lg bg-purple border-bottom border-body text-white"
  data-bs-theme="dark"
>
  <div class="container-fluid d-flex align-items-center justify-content-end">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul
        class="navbar-nav text-center d-flex align-items-center justify-content-center w-100"
      >
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/admin">Admin</a>
        </li>
      </ul>
    </div>
  </div>
</nav>